
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Felip
 */
public class AvaliacaoTela extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioTela
     */
    public AvaliacaoTela() {
        super("Avaliações");
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaliacaoPanel = new javax.swing.JPanel();
        tituloTextField = new javax.swing.JTextField();
        autorTextField = new javax.swing.JTextField();
        tipoUsuarioComboBox = new javax.swing.JComboBox<>();
        avaliacaoFilme1ComboBox = new javax.swing.JComboBox<>();
        avaliacaoFilme = new javax.swing.JLabel();
        comentarioLabel = new javax.swing.JLabel();
        cadastrarAvaliacaoButton = new javax.swing.JButton();
        cancelarAvaliacaoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentarioComboBox = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        avaliacaoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Comentário"));

        tituloTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o Título"));
        tituloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTextFieldActionPerformed(evt);
            }
        });

        autorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o Autor"));
        autorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorTextFieldActionPerformed(evt);
            }
        });

        tipoUsuarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "comum" }));

        avaliacaoFilme1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        avaliacaoFilme1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliacaoFilme1ComboBoxActionPerformed(evt);
            }
        });

        avaliacaoFilme.setText("Avaliação Filme");

        comentarioLabel.setText("Comentário: ");

        cadastrarAvaliacaoButton.setText("Cadastrar");
        cadastrarAvaliacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAvaliacaoButtonActionPerformed(evt);
            }
        });

        cancelarAvaliacaoButton.setText("Cancelar");
        cancelarAvaliacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAvaliacaoButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(comentarioComboBox);

        javax.swing.GroupLayout avaliacaoPanelLayout = new javax.swing.GroupLayout(avaliacaoPanel);
        avaliacaoPanel.setLayout(avaliacaoPanelLayout);
        avaliacaoPanelLayout.setHorizontalGroup(
            avaliacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avaliacaoPanelLayout.createSequentialGroup()
                .addGroup(avaliacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(avaliacaoPanelLayout.createSequentialGroup()
                        .addGroup(avaliacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoUsuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avaliacaoPanelLayout.createSequentialGroup()
                        .addComponent(cadastrarAvaliacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGroup(avaliacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(avaliacaoPanelLayout.createSequentialGroup()
                        .addGroup(avaliacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comentarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avaliacaoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avaliacaoFilme1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarAvaliacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        avaliacaoPanelLayout.setVerticalGroup(
            avaliacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avaliacaoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(avaliacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(avaliacaoPanelLayout.createSequentialGroup()
                        .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(autorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(tipoUsuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(avaliacaoPanelLayout.createSequentialGroup()
                        .addComponent(avaliacaoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(avaliacaoFilme1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(comentarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addGroup(avaliacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarAvaliacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarAvaliacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avaliacaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avaliacaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        avaliacaoPanel.getAccessibleContext().setAccessibleName("Cadastro de comentario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cancelarAvaliacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAvaliacaoButtonActionPerformed
        //DashboardTela dt = new DashboardTela(null);
        LoginTela lt = new LoginTela();
        lt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarAvaliacaoButtonActionPerformed

    private void cadastrarAvaliacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAvaliacaoButtonActionPerformed
       //Capturando informações da tela
       String titulo = tituloTextField.getText().trim();
       String autor = autorTextField.getText().trim();
       String tipo = (String) tipoUsuarioComboBox.getSelectedItem();
       String nota = (String)avaliacaoFilme1ComboBox.getSelectedItem();
       String comentario = comentarioComboBox.getText().trim();
       
       if (titulo.isEmpty() || autor.isEmpty() || comentario.isEmpty()){
           JOptionPane.showMessageDialog(this, "Preencha todos os campos. ", "Aviso", JOptionPane.WARNING_MESSAGE);
           return;
       }
       Avaliacao avaliacao = new Avaliacao(titulo, autor, tipo, nota, comentario);
       
       try {
            if (AvaliacaoDAO.consultaAvaliacao(avaliacao)) {
                JOptionPane.showMessageDialog(this, "Você já avaliou esse filme!", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                AvaliacaoDAO.cadastraAvaliacao(avaliacao);
                JOptionPane.showMessageDialog(this, "Avaliação cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }
        }

       catch(Exception e){
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
       }

    }//GEN-LAST:event_cadastrarAvaliacaoButtonActionPerformed

    private void tituloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTextFieldActionPerformed

    private void autorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorTextFieldActionPerformed

    private void avaliacaoFilme1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliacaoFilme1ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avaliacaoFilme1ComboBoxActionPerformed

    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(() -> new AvaliacaoTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autorTextField;
    private javax.swing.JLabel avaliacaoFilme;
    private javax.swing.JComboBox<String> avaliacaoFilme1ComboBox;
    private javax.swing.JPanel avaliacaoPanel;
    private javax.swing.JButton cadastrarAvaliacaoButton;
    private javax.swing.JButton cancelarAvaliacaoButton;
    private javax.swing.JTextPane comentarioComboBox;
    private javax.swing.JLabel comentarioLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> tipoUsuarioComboBox;
    private javax.swing.JTextField tituloTextField;
    // End of variables declaration//GEN-END:variables
}
