
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Felip
 */
public class FilmeTela extends javax.swing.JFrame {

    /**
     * Creates new form LivroTela
     */
    public FilmeTela() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filmePanel = new javax.swing.JPanel();
        cadastrarFilmejButton = new javax.swing.JButton();
        gerenciariFilmeLabel = new javax.swing.JLabel();
        tituloTextField = new javax.swing.JTextField();
        autorTextField = new javax.swing.JTextField();
        cancelarFilmejButton = new javax.swing.JButton();
        categComboBox = new javax.swing.JComboBox<>();
        usuarioTextField = new javax.swing.JTextField();
        btnListarFilmes = new javax.swing.JButton();
        sinopseTextField1 = new javax.swing.JTextField();
        anoComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filmes");

        javax.swing.GroupLayout filmePanelLayout = new javax.swing.GroupLayout(filmePanel);
        filmePanel.setLayout(filmePanelLayout);
        filmePanelLayout.setHorizontalGroup(
            filmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        filmePanelLayout.setVerticalGroup(
            filmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        cadastrarFilmejButton.setText("Cadastrar");
        cadastrarFilmejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFilmejButtonActionPerformed(evt);
            }
        });

        gerenciariFilmeLabel.setText("Cadastro de Filmes");

        tituloTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Título"));
        tituloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTextFieldActionPerformed(evt);
            }
        });

        autorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));
        autorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorTextFieldActionPerformed(evt);
            }
        });

        cancelarFilmejButton.setText("Cancelar");
        cancelarFilmejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarFilmejButtonActionPerformed(evt);
            }
        });

        categComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suspense  ", "Mistério  ", "Musical  ", "Guerra  ", "Biografia  ", "Documentário  ", "Faroeste  ", "Aventura  ", "Romance  ", "Fantasia  ", "Animação  ", "Família  ", "Comédia  ", "Drama  ", "Terror  ", "Ficção científica  ", "Ação  ", "Policial  ", " " }));
        categComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));
        categComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categComboBoxActionPerformed(evt);
            }
        });

        usuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome de Usuário"));

        btnListarFilmes.setText("Listar Filmes");
        btnListarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFilmesActionPerformed(evt);
            }
        });

        sinopseTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sinopse"));
        sinopseTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinopseTextField1ActionPerformed(evt);
            }
        });

        anoComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        anoComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ano"));
        anoComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(gerenciariFilmeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cadastrarFilmejButton)
                                        .addGap(122, 122, 122)
                                        .addComponent(btnListarFilmes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cancelarFilmejButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sinopseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                                .addComponent(categComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(autorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(filmePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filmePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gerenciariFilmeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sinopseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addComponent(anoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastrarFilmejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListarFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarFilmejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))))
        );

        sinopseTextField1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarFilmejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarFilmejButtonActionPerformed
        //DashboardTela dt = new DashboardTela();
        //dt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarFilmejButtonActionPerformed

    private void cadastrarFilmejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFilmejButtonActionPerformed
       // Captura os textos e remove espaços desnecessários
    String titulo = tituloTextField.getText().trim();
    String autor =  autorTextField.getText().trim();
    String sinopse = sinopseTextField1.getText().trim();
    String ano = anoComboBox1.getSelectedItem().toString();
    String categoria = categComboBox.getSelectedItem().toString();
    String usuarioCadastro = usuarioTextField.getText().trim();
    
    // Verificação básica se campos foram preenchidos
    if (titulo.isEmpty() || autor.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos (Título e Autor).");
        return;
    }

    // Cria o objeto Filme
    Filme filme = new Filme (titulo, autor, ano, categoria, sinopse, usuarioCadastro);

    // Tenta cadastrar no banco
    try {
        FilmeDAO.cadastraFilme(filme);
        JOptionPane.showMessageDialog(this, "Filme cadastrado com sucesso!");

        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar filme: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_cadastrarFilmejButtonActionPerformed

    private void autorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorTextFieldActionPerformed

    private void tituloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTextFieldActionPerformed

    private void btnListarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFilmesActionPerformed
    listarFilmes();
        
    }//GEN-LAST:event_btnListarFilmesActionPerformed

    private void categComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categComboBoxActionPerformed

    private void sinopseTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinopseTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinopseTextField1ActionPerformed

    private void anoComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoComboBox1ActionPerformed

   public void listarFilmes() {
    try {
        java.sql.Connection con = ConexaoBD.obtemConexao();
        String sql = "SELECT * FROM tb_filme ORDER BY titulo ASC"; // já ordena pelo título
        java.sql.PreparedStatement stmt = con.prepareStatement(sql);
        java.sql.ResultSet rs = stmt.executeQuery();

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Título");
        model.addColumn("Autor");
        model.addColumn("Ano");
        model.addColumn("Sinopse");
        model.addColumn("Categoria");
        model.addColumn("Usuário");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("titulo"),
                rs.getString("autor"),
                rs.getString("ano"),
                rs.getString("categoria"),
                rs.getString("usuario_cadastro")
            });
        }

        javax.swing.JTable tabela = new javax.swing.JTable(model);

        tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(150);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(230);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(180);

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(tabela);

        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.BorderLayout());
        panel.add(scrollPane, java.awt.BorderLayout.CENTER);

        javax.swing.JButton btnRemover = new javax.swing.JButton("Remover Filme");

        btnRemover.addActionListener(e -> {
            int selectedRow = tabela.getSelectedRow();
            if (selectedRow >= 0) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(
                        panel,
                        "Tem certeza que deseja remover este filme?",
                        "Confirmar remoção",
                        javax.swing.JOptionPane.YES_NO_OPTION
                );

                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    int idFilme = (int) model.getValueAt(selectedRow, 0);

                    try {
                        java.sql.Connection con2 = ConexaoBD.obtemConexao();
                        String deleteSQL = "DELETE FROM tb_filme WHERE id = ?";
                        java.sql.PreparedStatement deleteStmt = con2.prepareStatement(deleteSQL);
                        deleteStmt.setInt(1, idFilme);
                        deleteStmt.executeUpdate();

                        model.removeRow(selectedRow);

                        javax.swing.JOptionPane.showMessageDialog(panel, "Filme removido com sucesso!");

                        deleteStmt.close();
                        con2.close();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                        javax.swing.JOptionPane.showMessageDialog(panel, "Erro ao remover filme: " + ex.getMessage());
                    }
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(panel, "Selecione um filme para remover.");
            }
        });

        // Adiciona listener de duplo clique
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int selectedRow = tabela.getSelectedRow();
                    if (selectedRow >= 0) {
                        int idFilme = (int) model.getValueAt(selectedRow, 0);
                        String titulo = (String) model.getValueAt(selectedRow, 1);
                        String autor = (String) model.getValueAt(selectedRow, 2);
                        String sinopse = (String) model.getValueAt(selectedRow, 3);
                        String ano = (String) model.getValueAt(selectedRow, 4);
                        String categoria = (String) model.getValueAt(selectedRow, 5);
                        String usuario = (String) model.getValueAt(selectedRow, 6);

                        editarFilme(idFilme, titulo, autor, ano, categoria, sinopse, usuario, model, selectedRow);
                    }
                }
            }
        });

        javax.swing.JPanel southPanel = new javax.swing.JPanel();
        southPanel.add(btnRemover);

        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Lista de Filmes", true);
        dialog.setLayout(new java.awt.BorderLayout());
        dialog.add(panel, java.awt.BorderLayout.CENTER);
        dialog.add(southPanel, java.awt.BorderLayout.SOUTH);
        dialog.setSize(700, 400);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        rs.close();
        stmt.close();
        con.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao listar filmes: " + e.getMessage());
    }
}
private void editarFilme(
        int idFilme, 
        String titulo, 
        String autor, 
        String ano, 
        String categoria, 
        String sinopse, 
        String usuario, 
        javax.swing.table.DefaultTableModel model, 
        int rowIndex
) {
    javax.swing.JTextField tituloField = new javax.swing.JTextField(titulo);
    javax.swing.JTextField autorField = new javax.swing.JTextField(autor);
    javax.swing.JTextField sinopseField = new javax.swing.JTextField(sinopse);
    javax.swing.JTextField usuarioField = new javax.swing.JTextField(usuario);

    javax.swing.JComboBox<String> anoComboBox = new javax.swing.JComboBox<>(new String[] { "1950", "1955", "1960", /* ...*/"2025" });
    anoComboBox.setSelectedItem(ano);
    
    javax.swing.JComboBox<String> categComboBox = new javax.swing.JComboBox<>(new String[] { "ação", "tecnologia", "aventura" });
    categComboBox.setSelectedItem(categoria);

    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1));
    panel.add(new javax.swing.JLabel("Título:"));
    panel.add(tituloField);
    panel.add(new javax.swing.JLabel("Autor:"));
    panel.add(autorField);
    panel.add(new javax.swing.JLabel("Sinopse:"));
    panel.add(sinopseField);
    panel.add(new javax.swing.JLabel("Ano:"));
    panel.add(anoComboBox);
    panel.add(new javax.swing.JLabel("Categoria:"));
    panel.add(categComboBox);
    panel.add(new javax.swing.JLabel("Usuário:"));
    panel.add(usuarioField);

    int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Editar Filme", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);

    if (result == javax.swing.JOptionPane.OK_OPTION) {
        try {
            java.sql.Connection con = ConexaoBD.obtemConexao();
            String updateSQL = "UPDATE tb_filme SET titulo = ?, autor = ?, ano = ?, usuario_cadastro = ? WHERE id = ?";
            java.sql.PreparedStatement stmt = con.prepareStatement(updateSQL);

            stmt.setString(1, tituloField.getText().trim());
            stmt.setString(2, autorField.getText().trim());
            stmt.setString(3, anoComboBox.getSelectedItem().toString());
            stmt.setString(4, categComboBox.getSelectedItem().toString());
            stmt.setString(5, usuarioField.getText().trim());
            stmt.setInt(6, idFilme);

            stmt.executeUpdate();

            model.setValueAt(tituloField.getText().trim(), rowIndex, 1);
            model.setValueAt(autorField.getText().trim(), rowIndex, 2);
            model.setValueAt(sinopseField.getText().trim(), rowIndex, 3);
            model.setValueAt(anoComboBox.getSelectedItem().toString(), rowIndex, 4);
            model.setValueAt(categComboBox.getSelectedItem().toString(), rowIndex, 5);
            model.setValueAt(usuarioField.getText().trim(), rowIndex, 6);

            javax.swing.JOptionPane.showMessageDialog(this, "Filme atualizado com sucesso!");

            stmt.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao atualizar filme: " + e.getMessage());
        }
    }
}
    
    
   
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmeTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anoComboBox1;
    private javax.swing.JTextField autorTextField;
    private javax.swing.JButton btnListarFilmes;
    private javax.swing.JButton cadastrarFilmejButton;
    private javax.swing.JButton cancelarFilmejButton;
    private javax.swing.JComboBox<String> categComboBox;
    private javax.swing.JPanel filmePanel;
    private javax.swing.JLabel gerenciariFilmeLabel;
    private javax.swing.JTextField sinopseTextField1;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
